package com.ticket.repository;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

public class DatabaseConnection {
    private static final String DEFAULT_URL = "jdbc:oracle:thin:@//localhost:1521/ORCL";
    private static final String DEFAULT_SID_URL = "jdbc:oracle:thin:@localhost:1521:ORCL";
    private static final String DEFAULT_USER = "system";
    private static final String DEFAULT_PASSWORD = "oracle";

    public static Connection getConnection() {
        loadDotEnvIfPresent();

        Connection connection = null;
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            String url = getSetting("DB_URL", DEFAULT_URL);
            String user = getSetting("DB_USER", DEFAULT_USER);
            String password = getSetting("DB_PASSWORD", DEFAULT_PASSWORD);

            connection = DriverManager.getConnection(url, user, password);
            if (connection != null) {
                System.out.println("ĐÃ KẾT NỐI ORACLE THÀNH CÔNG!");
            }
        } catch (ClassNotFoundException e) {
            System.err.println("LỖI: Thiếu file ojdbc8.jar!");
        } catch (SQLException e) {
            System.err.println("LỖI KẾT NỐI DATABASE: " + e.getMessage());
            try {
                String sidUrl = getSetting("DB_SID_URL", DEFAULT_SID_URL);
                String user = getSetting("DB_USER", DEFAULT_USER);
                String password = getSetting("DB_PASSWORD", DEFAULT_PASSWORD);
                connection = DriverManager.getConnection(sidUrl, user, password);
                if (connection != null) System.out.println("ĐÃ KẾT NỐI ORACLE THÀNH CÔNG!");
            } catch (SQLException e2) {
                System.err.println("KẾT NỐI THẤT BẠI");
            }
        }
        return connection;
    }

    private static String getSetting(String key, String defaultValue) {
        String value = System.getProperty(key);
        if (value == null || value.isBlank()) {
            value = System.getenv(key);
        }
        if (value == null || value.isBlank()) {
            return defaultValue;
        }
        return value;
    }

    private static void loadDotEnvIfPresent() {
        if (System.getProperty("DB_URL") != null
                || System.getProperty("DB_USER") != null
                || System.getProperty("DB_PASSWORD") != null
                || System.getProperty("DB_SID_URL") != null) {
            return;
        }

        Path envPath = Path.of(".env");
        if (!Files.exists(envPath)) {
            return;
        }

        try {
            List<String> lines = Files.readAllLines(envPath, StandardCharsets.UTF_8);
            for (String rawLine : lines) {
                if (rawLine == null) continue;
                String line = rawLine.trim();
                if (line.isEmpty()) continue;
                if (line.startsWith("#")) continue;

                int idx = line.indexOf('=');
                if (idx <= 0) continue;

                String key = line.substring(0, idx).trim();
                String value = line.substring(idx + 1).trim();

                if ((value.startsWith("\"") && value.endsWith("\""))
                        || (value.startsWith("'") && value.endsWith("'"))) {
                    value = value.substring(1, value.length() - 1);
                }

                if (!key.isEmpty() && System.getProperty(key) == null) {
                    System.setProperty(key, value);
                }
            }
        } catch (IOException ignored) {
        }
    }

    public static void initDatabase() {
        Connection conn = getConnection();
        if (conn == null) {
            System.err.println("KHÔNG THỂ KHỞI TẠO DB: Kết nối đang bị NULL!");
            return;
        }

        try (Statement stmt = conn.createStatement()) {
            String usersSQL = "CREATE TABLE USERS (" +
                    "ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "USERNAME VARCHAR2(50) UNIQUE NOT NULL, " +
                    "PASSWORD VARCHAR2(100) NOT NULL, " +
                    "FULL_NAME VARCHAR2(100), " +
                    "ROLE VARCHAR2(20) DEFAULT 'USER', " +
                    "CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP)";
            executeCreateTable(stmt, "USERS", usersSQL);
            // thông tin chuyến đi
            String tripsSQL = "CREATE TABLE TRIPS (" +
                    "ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "TRIP_NAME VARCHAR2(100) NOT NULL, " +
                    "START_LOCATION VARCHAR2(100), " +
                    "END_LOCATION VARCHAR2(100), " +
                    "DEPARTURE_TIME TIMESTAMP, " +
                    "BASE_PRICE NUMBER(10,2), " +
                    "TOTAL_SEATS NUMBER(3), " +
                    "AVAILABLE_SEATS NUMBER(3))";
            executeCreateTable(stmt, "TRIPS", tripsSQL);

            String bookingsSQL = "CREATE TABLE BOOKINGS (" +
                    "ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "BOOKING_CODE VARCHAR2(20) UNIQUE NOT NULL, " +
                    "USER_ID NUMBER REFERENCES USERS(ID), " +
                    "TRIP_ID NUMBER REFERENCES TRIPS(ID), " +
                    "BOOKING_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
                    "TOTAL_AMOUNT NUMBER(10,2), " +
                    "STATUS VARCHAR2(20) DEFAULT 'PENDING' CHECK (STATUS IN ('PENDING', 'CONFIRMED', 'CANCELLED')), " +
                    "PAYMENT_METHOD VARCHAR2(20))";
            executeCreateTable(stmt, "BOOKINGS", bookingsSQL);

            seedData(stmt);

        } catch (SQLException e) {
            e.printStackTrace();
        } finally {
            try { if (conn != null) conn.close(); } catch (SQLException e) {}
        }
    }

    private static void executeCreateTable(Statement stmt, String tableName, String sql) throws SQLException {
        try {
            stmt.execute(sql);
            System.out.println("Đã tạo bảng " + tableName + " thành công!");
        } catch (SQLException e) {
            if (e.getErrorCode() == 955) {
                System.out.println("Bảng " + tableName + " đã tồn tại.");
            } else {
                throw e;
            }
        }
    }

    private static void seedData(Statement stmt) throws SQLException {
        // 1. Chèn admin mặc định
        try {
            stmt.execute("INSERT INTO USERS (USERNAME, PASSWORD, FULL_NAME, ROLE) VALUES ('admin', 'admin123', 'Administrator', 'ADMIN')");
            System.out.println(">>> Đã tạo tài khoản admin mặc định.");
        } catch (SQLException e) {}

        // 2. Chèn chuyến đi mẫu
        try {
            stmt.execute("INSERT INTO TRIPS (TRIP_NAME, START_LOCATION, END_LOCATION, BASE_PRICE, TOTAL_SEATS, AVAILABLE_SEATS) " +
                        "VALUES ('Hanoi - Da Nang', 'Hanoi', 'Da Nang', 150.0, 40, 35)");
            stmt.execute("INSERT INTO TRIPS (TRIP_NAME, START_LOCATION, END_LOCATION, BASE_PRICE, TOTAL_SEATS, AVAILABLE_SEATS) " +
                        "VALUES ('Saigon - Nha Trang', 'Saigon', 'Nha Trang', 120.0, 30, 20)");
            System.out.println(">>> Đã chèn dữ liệu Trip mẫu.");
        } catch (SQLException e) {}

        // 3. Chèn Booking mẫu (Liên kết User ID 1 và Trip ID 1)
        try {
            stmt.execute("INSERT INTO BOOKINGS (BOOKING_CODE, USER_ID, TRIP_ID, TOTAL_AMOUNT, STATUS, PAYMENT_METHOD) " +
                        "VALUES ('BK-888', 1, 1, 150.0, 'CONFIRMED', 'CREDIT_CARD')");
            stmt.execute("INSERT INTO BOOKINGS (BOOKING_CODE, USER_ID, TRIP_ID, TOTAL_AMOUNT, STATUS, PAYMENT_METHOD) " +
                        "VALUES ('BK-999', 1, 2, 120.0, 'PENDING', 'CASH')");
            stmt.execute("INSERT INTO BOOKINGS (BOOKING_CODE, USER_ID, TRIP_ID, TOTAL_AMOUNT, STATUS, PAYMENT_METHOD) " +
                        "VALUES ('BK-000', 1, 1, 150.0, 'CANCELLED', 'E-WALLET')");
            System.out.println(">>> Đã chèn dữ liệu Booking mẫu.");
        } catch (SQLException e) {}
    }


    public static void main(String[] args) {
        initDatabase();
    }
}

