
DELETE FROM BOOKINGS;
DELETE FROM COUPONS;
DELETE FROM CUSTOMERS;
DELETE FROM TRIPS;
DELETE FROM ACCOUNTS;


INSERT INTO ACCOUNTS (ID, USERNAME, PASSWORD, FULL_NAME, ROLE, PHONE_NUMBER) VALUES (1, 'admin', 'admin123', 'Administrator', 'ADMIN', '0900000000');
INSERT INTO ACCOUNTS (ID, USERNAME, PASSWORD, FULL_NAME, ROLE, PHONE_NUMBER) VALUES (2, 'staff01', 'staff123', 'Nguyen Van Minh', 'STAFF', '0901000001');
INSERT INTO ACCOUNTS (ID, USERNAME, PASSWORD, FULL_NAME, ROLE, PHONE_NUMBER) VALUES (3, 'staff02', 'staff123', 'Tran Thi Lan', 'STAFF', '0901000002');
INSERT INTO ACCOUNTS (ID, USERNAME, PASSWORD, FULL_NAME, ROLE, PHONE_NUMBER) VALUES (4, 'staff03', 'staff123', 'Le Van Hung', 'STAFF', '0901000003');
INSERT INTO ACCOUNTS (ID, USERNAME, PASSWORD, FULL_NAME, ROLE, PHONE_NUMBER) VALUES (5, 'staff04', 'staff123', 'Pham Thi Mai', 'STAFF', '0901000004');
INSERT INTO ACCOUNTS (ID, USERNAME, PASSWORD, FULL_NAME, ROLE, PHONE_NUMBER) VALUES (6, 'staff05', 'staff123', 'Hoang Van Nam', 'STAFF', '0901000005');
INSERT INTO ACCOUNTS (ID, USERNAME, PASSWORD, FULL_NAME, ROLE, PHONE_NUMBER) VALUES (7, 'manager01', 'manager1', 'Dang Thi Huong', 'ADMIN', '0902000001');
INSERT INTO ACCOUNTS (ID, USERNAME, PASSWORD, FULL_NAME, ROLE, PHONE_NUMBER) VALUES (8, 'staff06', 'staff123', 'Bui Van Phuc', 'STAFF', '0901000006');
INSERT INTO ACCOUNTS (ID, USERNAME, PASSWORD, FULL_NAME, ROLE, PHONE_NUMBER) VALUES (9, 'staff07', 'staff123', 'Vo Thi Nhung', 'STAFF', '0901000007');
INSERT INTO ACCOUNTS (ID, USERNAME, PASSWORD, FULL_NAME, ROLE, PHONE_NUMBER) VALUES (10, 'staff08', 'staff123', 'Nguyen Van Thanh', 'STAFF', '0901000008');


INSERT INTO TRIPS (ID, TRIP_NAME, START_LOCATION, END_LOCATION, DEPARTURE_TIME, BASE_PRICE, TOTAL_SEATS, AVAILABLE_SEATS) VALUES (1, 'Ha Noi - Da Nang', 'Ha Noi', 'Da Nang', TIMESTAMP '2026-07-10 06:00:00', 150000, 40, 35);
INSERT INTO TRIPS (ID, TRIP_NAME, START_LOCATION, END_LOCATION, DEPARTURE_TIME, BASE_PRICE, TOTAL_SEATS, AVAILABLE_SEATS) VALUES (2, 'Sai Gon - Nha Trang', 'Sai Gon', 'Nha Trang', TIMESTAMP '2026-07-10 08:00:00', 120000, 30, 20);
INSERT INTO TRIPS (ID, TRIP_NAME, START_LOCATION, END_LOCATION, DEPARTURE_TIME, BASE_PRICE, TOTAL_SEATS, AVAILABLE_SEATS) VALUES (3, 'Ha Noi - Hai Phong', 'Ha Noi', 'Hai Phong', TIMESTAMP '2026-07-11 05:30:00', 80000, 35, 30);
INSERT INTO TRIPS (ID, TRIP_NAME, START_LOCATION, END_LOCATION, DEPARTURE_TIME, BASE_PRICE, TOTAL_SEATS, AVAILABLE_SEATS) VALUES (4, 'Sai Gon - Da Lat', 'Sai Gon', 'Da Lat', TIMESTAMP '2026-07-11 07:00:00', 180000, 30, 25);
INSERT INTO TRIPS (ID, TRIP_NAME, START_LOCATION, END_LOCATION, DEPARTURE_TIME, BASE_PRICE, TOTAL_SEATS, AVAILABLE_SEATS) VALUES (5, 'Da Nang - Hue', 'Da Nang', 'Hue', TIMESTAMP '2026-07-12 09:00:00', 60000, 35, 32);
INSERT INTO TRIPS (ID, TRIP_NAME, START_LOCATION, END_LOCATION, DEPARTURE_TIME, BASE_PRICE, TOTAL_SEATS, AVAILABLE_SEATS) VALUES (6, 'Can Tho - Sai Gon', 'Can Tho', 'Sai Gon', TIMESTAMP '2026-07-12 06:30:00', 130000, 35, 28);
INSERT INTO TRIPS (ID, TRIP_NAME, START_LOCATION, END_LOCATION, DEPARTURE_TIME, BASE_PRICE, TOTAL_SEATS, AVAILABLE_SEATS) VALUES (7, 'Ha Noi - Sa Pa', 'Ha Noi', 'Sa Pa', TIMESTAMP '2026-07-13 22:00:00', 200000, 30, 25);
INSERT INTO TRIPS (ID, TRIP_NAME, START_LOCATION, END_LOCATION, DEPARTURE_TIME, BASE_PRICE, TOTAL_SEATS, AVAILABLE_SEATS) VALUES (8, 'Sai Gon - Phan Thiet', 'Sai Gon', 'Phan Thiet', TIMESTAMP '2026-07-13 07:30:00', 110000, 35, 30);
INSERT INTO TRIPS (ID, TRIP_NAME, START_LOCATION, END_LOCATION, DEPARTURE_TIME, BASE_PRICE, TOTAL_SEATS, AVAILABLE_SEATS) VALUES (9, 'Vinh - Ha Noi', 'Vinh', 'Ha Noi', TIMESTAMP '2026-07-14 19:00:00', 160000, 40, 35);
INSERT INTO TRIPS (ID, TRIP_NAME, START_LOCATION, END_LOCATION, DEPARTURE_TIME, BASE_PRICE, TOTAL_SEATS, AVAILABLE_SEATS) VALUES (10, 'Da Nang - Sai Gon', 'Da Nang', 'Sai Gon', TIMESTAMP '2026-07-14 15:00:00', 320000, 35, 30);
INSERT INTO TRIPS (ID, TRIP_NAME, START_LOCATION, END_LOCATION, DEPARTURE_TIME, BASE_PRICE, TOTAL_SEATS, AVAILABLE_SEATS) VALUES (11, 'Ha Noi - Thanh Hoa', 'Ha Noi', 'Thanh Hoa', TIMESTAMP '2026-07-15 06:00:00', 100000, 30, 27);
INSERT INTO TRIPS (ID, TRIP_NAME, START_LOCATION, END_LOCATION, DEPARTURE_TIME, BASE_PRICE, TOTAL_SEATS, AVAILABLE_SEATS) VALUES (12, 'Nha Trang - Da Nang', 'Nha Trang', 'Da Nang', TIMESTAMP '2026-07-15 08:30:00', 170000, 35, 30);


INSERT INTO CUSTOMERS (ID, FULL_NAME, PHONE_NUMBER, EMAIL) VALUES (1, 'Nguyen Van An', '0987654321', 'an.nguyen@gmail.com');
INSERT INTO CUSTOMERS (ID, FULL_NAME, PHONE_NUMBER, EMAIL) VALUES (2, 'Tran Thi Bich', '0912345678', 'bich.tran@yahoo.com');
INSERT INTO CUSTOMERS (ID, FULL_NAME, PHONE_NUMBER, EMAIL) VALUES (3, 'Le Van Cuong', '0923456789', 'cuong.le@outlook.com');
INSERT INTO CUSTOMERS (ID, FULL_NAME, PHONE_NUMBER, EMAIL) VALUES (4, 'Pham Thi Dung', '0934567890', 'dung.pham@gmail.com');
INSERT INTO CUSTOMERS (ID, FULL_NAME, PHONE_NUMBER, EMAIL) VALUES (5, 'Hoang Van Em', '0945678901', 'em.hoang@gmail.com');
INSERT INTO CUSTOMERS (ID, FULL_NAME, PHONE_NUMBER, EMAIL) VALUES (6, 'Vo Thi Phuong', '0956789012', 'phuong.vo@yahoo.com');
INSERT INTO CUSTOMERS (ID, FULL_NAME, PHONE_NUMBER, EMAIL) VALUES (7, 'Bui Van Giap', '0967890123', 'giap.bui@gmail.com');
INSERT INTO CUSTOMERS (ID, FULL_NAME, PHONE_NUMBER, EMAIL) VALUES (8, 'Dang Thi Hong', '0978901234', 'hong.dang@outlook.com');
INSERT INTO CUSTOMERS (ID, FULL_NAME, PHONE_NUMBER, EMAIL) VALUES (9, 'Ngo Van Ich', '0989012345', 'ich.ngo@gmail.com');
INSERT INTO CUSTOMERS (ID, FULL_NAME, PHONE_NUMBER, EMAIL) VALUES (10, 'Do Thi Khanh', '0990123456', 'khanh.do@yahoo.com');


INSERT INTO COUPONS (ID, CODE, DISCOUNT_PERCENT, DISCOUNT_AMOUNT, EXPIRED_DATE, IS_ACTIVE) VALUES (1, 'SUMMER10', 10, NULL, DATE '2026-09-30', 1);
INSERT INTO COUPONS (ID, CODE, DISCOUNT_PERCENT, DISCOUNT_AMOUNT, EXPIRED_DATE, IS_ACTIVE) VALUES (2, 'WELCOME20', 20, NULL, DATE '2026-08-31', 1);
INSERT INTO COUPONS (ID, CODE, DISCOUNT_PERCENT, DISCOUNT_AMOUNT, EXPIRED_DATE, IS_ACTIVE) VALUES (3, 'FLAT50K', NULL, 50000, DATE '2026-12-31', 1);
INSERT INTO COUPONS (ID, CODE, DISCOUNT_PERCENT, DISCOUNT_AMOUNT, EXPIRED_DATE, IS_ACTIVE) VALUES (4, 'TET2026', 15, NULL, DATE '2026-07-15', 1);
INSERT INTO COUPONS (ID, CODE, DISCOUNT_PERCENT, DISCOUNT_AMOUNT, EXPIRED_DATE, IS_ACTIVE) VALUES (5, 'VIP25', 25, NULL, DATE '2026-10-31', 1);
INSERT INTO COUPONS (ID, CODE, DISCOUNT_PERCENT, DISCOUNT_AMOUNT, EXPIRED_DATE, IS_ACTIVE) VALUES (6, 'FLAT30K', NULL, 30000, DATE '2026-08-31', 1);
INSERT INTO COUPONS (ID, CODE, DISCOUNT_PERCENT, DISCOUNT_AMOUNT, EXPIRED_DATE, IS_ACTIVE) VALUES (7, 'STUDENT5', 5, NULL, DATE '2026-12-31', 1);
INSERT INTO COUPONS (ID, CODE, DISCOUNT_PERCENT, DISCOUNT_AMOUNT, EXPIRED_DATE, IS_ACTIVE) VALUES (8, 'EXPIRED50', 50, NULL, DATE '2025-01-01', 0);
INSERT INTO COUPONS (ID, CODE, DISCOUNT_PERCENT, DISCOUNT_AMOUNT, EXPIRED_DATE, IS_ACTIVE) VALUES (9, 'HOLIDAY15', 15, NULL, DATE '2026-09-15', 1);
INSERT INTO COUPONS (ID, CODE, DISCOUNT_PERCENT, DISCOUNT_AMOUNT, EXPIRED_DATE, IS_ACTIVE) VALUES (10, 'FLAT100K', NULL, 100000, DATE '2026-11-30', 1);


DECLARE
    v_trip_ids SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST(1,2,3,4,5,6,7,8,9,10,11,12);
    v_cust_ids SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST(1,2,3,4,5,6,7,8,9,10);
    v_staff_ids SYS.ODCINUMBERLIST := SYS.ODCINUMBERLIST(1,2,3,4,5,6,7,8,9,10);
    v_statuses SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST('PENDING','CONFIRMED','CANCELLED');
    v_payments SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST('CASH','CREDIT_CARD','E-WALLET');
    v_coupons SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST('SUMMER10','WELCOME20','FLAT50K','VIP25','FLAT30K',NULL,NULL,NULL,NULL,NULL);
    v_trip_id NUMBER;
    v_cust_id NUMBER;
    v_staff_id NUMBER;
    v_status VARCHAR2(20);
    v_payment VARCHAR2(20);
    v_seats NUMBER;
    v_price NUMBER;
    v_amount NUMBER;
    v_coupon VARCHAR2(50);
    v_booking_date TIMESTAMP;
    v_bcode VARCHAR2(20);
BEGIN
    FOR i IN 1..100 LOOP
        v_trip_id := v_trip_ids(TRUNC(DBMS_RANDOM.VALUE(1, 13)));
        v_cust_id := v_cust_ids(TRUNC(DBMS_RANDOM.VALUE(1, 11)));
        v_staff_id := v_staff_ids(TRUNC(DBMS_RANDOM.VALUE(1, 11)));

        v_status := CASE
            WHEN DBMS_RANDOM.VALUE(1, 101) <= 60 THEN 'CONFIRMED'
            WHEN DBMS_RANDOM.VALUE(1, 101) <= 85 THEN 'PENDING'
            ELSE 'CANCELLED'
        END;

        v_payment := v_payments(TRUNC(DBMS_RANDOM.VALUE(1, 4)));
        v_seats := TRUNC(DBMS_RANDOM.VALUE(1, 6));
        v_coupon := v_coupons(TRUNC(DBMS_RANDOM.VALUE(1, 11)));

        SELECT BASE_PRICE INTO v_price FROM TRIPS WHERE ID = v_trip_id;
        v_amount := v_price * v_seats;

        IF v_coupon IS NOT NULL THEN
            FOR c IN (SELECT * FROM COUPONS WHERE CODE = v_coupon AND ROWNUM = 1) LOOP
                IF c.DISCOUNT_PERCENT IS NOT NULL THEN
                    v_amount := v_amount - (v_amount * c.DISCOUNT_PERCENT / 100);
                ELSIF c.DISCOUNT_AMOUNT IS NOT NULL THEN
                    v_amount := v_amount - c.DISCOUNT_AMOUNT;
                END IF;
            END LOOP;
        END IF;
        IF v_amount < 0 THEN v_amount := 0; END IF;

        v_booking_date := SYSTIMESTAMP - NUMTODSINTERVAL(TRUNC(DBMS_RANDOM.VALUE(0, 60)), 'DAY');

        v_bcode := 'BK-' || TO_CHAR(i);

        INSERT INTO BOOKINGS (ID, BOOKING_CODE, CREATED_BY, CUSTOMER_ID, TRIP_ID,
                              BOOKING_DATE, TOTAL_SEATS, TOTAL_AMOUNT, STATUS,
                              PAYMENT_METHOD, COUPON_CODE)
        VALUES (i, v_bcode, v_staff_id, v_cust_id, v_trip_id,
                v_booking_date, v_seats, ROUND(v_amount, 0), v_status,
                v_payment, v_coupon);
    END LOOP;
    COMMIT;
END;
/

SELECT 'ACCOUNTS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM ACCOUNTS
UNION ALL
SELECT 'TRIPS', COUNT(*) FROM TRIPS
UNION ALL
SELECT 'CUSTOMERS', COUNT(*) FROM CUSTOMERS
UNION ALL
SELECT 'COUPONS', COUNT(*) FROM COUPONS
UNION ALL
SELECT 'BOOKINGS', COUNT(*) FROM BOOKINGS;

PROMPT Seed data created successfully!
